### ISSUE TITLE
Grandnode can not complete the installation and make my ec2 instance unresponsive

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [grandnode/grandnode#254]
I tried to create a new instance and tested it, it did the same.

ec2 instance: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180522
docker image: grandnode/grandnode:4.10

**Comment by PatrykPorabik** [comment]
Hi,
Could you describe this problem more? You saw the installation screen and it threw error during the application installation? What we should do to simulate this issue? Could you tell us a each step which you made?

Best,
Patryk

**Comment by ClassicDarkChocolate** [comment]
@PatrykPorabik
Steps to reproduce:

1. Create a t2.micro instance
2. Install docker
3. Create `docker-compose.yml`

```
version: "3.6"

services:
  mongo:
    image: mongo:3.6
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_configdb:/data/configdb
    ports:
      - 27017:27017
  grandnode:
    image: grandnode/grandnode:4.10
    ports:
      - 8080:8080
    depends_on:
      - mongo

volumes:
  mongo_data_db:
    external: true
  mongo_data_configdb:
    external: true
```

4. `docker stack deploy -c docker-compose.yml grandnode`
5. Fill in installation form.
6. The webpage displayed installed.
7. The instance is unresponsive. Can not connect to the instance through ssh. All the other deployed services are unresponsive.
